require('plugins')
require('settings')
require('keymappings')
require('theme')

require('plugins/nvim-tree')
require('plugins/tree-sitter')
require('plugins/lsp-installer')
require('plugins/lspconfig')
require('plugins/lspkind')
require('plugins/cmp')

require('plugins/barbar')
require('plugins/galaxyline')
require('plugins/telescope')
require('plugins/Comment')
require('plugins/dashboard')
require('plugins/colorizer')
require('plugins/which-key')
require('plugins/terminal')
require('plugins/vsnip')

